[38] form validation
funny-code-404/js-course pull request #55
Opened 2021-09-27 14:06 UTC by nbruyok

2021-09-28 15:26 UTC, funny-code-404 approved these changes

2021-09-28 15:26 UTC, funny-code-404 commented on 38/bruyok/r-form-validation/src/components/Form/Form.js
> +    let errors = this.state.errors;
так делать нельзя, ты копируешь ссылку на объект, и как следствие, меняешь state напрямую. ты можешь копировать state используя spread-operator

2021-09-28 15:27 UTC, funny-code-404 requested changes
хорошее Д/З! поправь один комментарий, пожалуйста

2021-10-01 12:05 UTC, nbruyok commented on 38/bruyok/r-form-validation/src/components/Form/Form.js
> +    let errors = this.state.errors;
исправила)

2021-10-05 19:27 UTC, funny-code-404 approved these changes

2021-10-05 19:27 UTC, merged