make tests for function
funny-code-404/js-course pull request #65
Opened 2021-11-25 20:04 UTC by balerosha

2021-11-25 23:13 UTC, funny-code-404 requested changes

2021-11-25 23:13 UTC, funny-code-404 commented on 32/Trekalo Valera/__test__/index.test.js
> +const message = "Not correct arguments";
используй комбинацию beforeEach  и переменной let (я просил повитать  про этот метод)

2021-11-25 23:13 UTC, funny-code-404 commented on 32/Trekalo Valera/__test__/index.test.js
> +  expect(invitation(obj)).toEqual("Hello! My name is Valera. I am 23");
можно было исполльзовать toBe

2021-11-26 19:52 UTC, balerosha commented
понажимал лишнего, но это случайно )

2021-11-28 14:31 UTC, funny-code-404 approved these changes

2021-11-28 14:31 UTC, merged