37-Homerwork/ made page with React
funny-code-404/js-course pull request #78
Opened 2021-12-17 12:51 UTC by balerosha

2021-12-23 17:34 UTC, funny-code-404 requested changes

2021-12-23 17:34 UTC, funny-code-404 commented on 37/Trekalo V/src/App.jsx
> +// import { Header } from "./components/Header";
убери комметарии, если не планируешь их использовать

2021-12-23 17:34 UTC, funny-code-404 commented on 37/Trekalo V/src/components/Header/components/Button/index.jsx
> +import "./styles.css";
импортируй стили после реакта

2021-12-23 17:34 UTC, funny-code-404 commented on 37/Trekalo V/src/components/Header/components/Button/index.jsx
> +  // console.log(props);
то же самое

2021-12-23 17:34 UTC, funny-code-404 commented on 37/Trekalo V/src/components/Header/components/Title/index.jsx
> +    <div className={classes.block}>
почему ты классы передаешь через пропсы? не будет ли удобнее для данного компонента определить в директории с самим компонентом?

2021-12-23 17:34 UTC, funny-code-404 commented on 37/Trekalo V/src/components/Header/index.jsx
> +          <Button text="HIRE IS NOW" />
постарайся перенести значения строк в отдельные переменные в отдельных файлах

2021-12-23 17:34 UTC, funny-code-404 commented on 37/Trekalo V/src/components/Navigation/components/Logo/index.jsx
> +      <p className="logo">Your Logo</p>
то же самое - строки - передавай или через пропсы или через константы из отдельных файлов

2021-12-23 18:02 UTC, balerosha commented on 37/Trekalo V/src/components/Header/components/Title/index.jsx
> +    <div className={classes.block}>
Это была первая дз с использованием реакта, и хотел повпихивать работу с пропсами, чтоб руку набить, понимаю, что это тут не нужно)

2022-01-17 13:39 UTC, funny-code-404 approved these changes

2022-01-17 13:39 UTC, merged